package gui;

import data.LoginPerson;
import db.DBLoginAccess;
import javax.swing.JOptionPane;

/**
 * JDialog RegisterDlg.
 * 
 * @author Herbert Seewann
 * @version 6.0
 */
public class RegisterDlg extends javax.swing.JDialog {
    
    private DBLoginAccess dba;
    
    /**
     * Creates new form RegisterDlg
     */
    public RegisterDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dba = DBLoginAccess.getInstance();
        rbVorstand.setActionCommand("Vorstand");
        rbTrainer.setActionCommand("Trainer");
        rbSpieler.setActionCommand("Spieler");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgArt = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rbVorstand = new javax.swing.JRadioButton();
        rbTrainer = new javax.swing.JRadioButton();
        rbSpieler = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        btRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(5, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrieren");
        getContentPane().add(jLabel1);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jLabel4.setText("Art auswählen:");
        jPanel3.add(jLabel4);

        jPanel4.setLayout(new java.awt.GridLayout(3, 1));

        bgArt.add(rbVorstand);
        rbVorstand.setSelected(true);
        rbVorstand.setText("Vorstand");
        jPanel4.add(rbVorstand);

        bgArt.add(rbTrainer);
        rbTrainer.setText("Trainer");
        jPanel4.add(rbTrainer);

        bgArt.add(rbSpieler);
        rbSpieler.setText("Spieler");
        jPanel4.add(rbSpieler);

        jPanel3.add(jPanel4);

        getContentPane().add(jPanel3);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setText("Username wählen:");
        jPanel1.add(jLabel2);
        jPanel1.add(tfUsername);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jLabel3.setText("Passwort wählen:");
        jPanel2.add(jLabel3);
        jPanel2.add(tfPassword);

        getContentPane().add(jPanel2);

        btRegister.setText("Registrieren");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btRegister);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        try {
            if(tfPassword.getText().equals("") || tfUsername.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Bitte alle Pflichtfelder ausfüllen!");
            } else if(dba.isUsernameThere(tfUsername.getText())) {
                JOptionPane.showMessageDialog(this, "Benutzer existiert bereits!");
            } else {
                LoginPerson p = new LoginPerson(bgArt.getSelection().getActionCommand(),
                tfUsername.getText(), tfPassword.getText());
                dba.persistEntity(p);
                this.dispose();
                LoginDlg.main(null);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btRegisterActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterDlg dialog = new RegisterDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgArt;
    private javax.swing.JButton btRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rbSpieler;
    private javax.swing.JRadioButton rbTrainer;
    private javax.swing.JRadioButton rbVorstand;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
